### ISSUE TITLE
Back up all the DO NOT REMOVE issues as markdown files in this repo.

### ISSUE THREAD

**Issue by sadasant** [tecnoyucas/meta#21]
Just to be extra safe, let's make a copy of the latest state of all of these issues in markdown files in this repo. The git repo will probably survive more than the issues themselves.

**Comment by stefanmaric** [comment]
I was thinking on simply projecting the content of those "do not remove" issues on whatever markdown file they best fit, once those issues become stale, to give the community some time to react and discuss. Because most of those issues are either a description of the project itself or contribution guidelines.

**Comment by sadasant** [comment]
@stefanmaric Yes! I believe we're saying the same thing. What do you mean by projecting? What I had on my head was just to make markdown files like `Our-Goals.md` at the root of this project, then link them in the README. Perhaps linking them in the README isn't urgent, but a backup seems safe todo asap.

**Comment by stefanmaric** [comment]
I meant like taking whatever was agreed on in those issues and distribute them among README, CONTRIBUTING, etc appropriately – once we agree on those issues.

And I'm not really understanding the ASAP bit; did you get news about GitHub bankruptcy or something?

**Comment by sadasant** [comment]
@stefanmaric well, github issues don't have version control and can be edited by more than one person, it's just about that 🌞

**Comment by sadasant** [comment]
@aitbw :0 thanks! Can I assign this to you then?

**Comment by aitbw** [comment]
Yes, no problem @sadasant  :)
